#!/usr/bin/env python3
"""Prepare QUEST1 OpenQP MRSF-TDDFT inputs.

This script does not run OpenQP unless --run is passed. By default it extracts
the selected QUEST1 xyz files from QUESTDB-main.zip and writes .inp files with
a triplet ROHF reference followed by MRSF-TDDFT.
"""

from __future__ import annotations

import argparse
import subprocess
import zipfile
from dataclasses import dataclass
from pathlib import Path


WORK_DIR = Path(__file__).resolve().parent
ZIP_PATH = WORK_DIR / "QUESTDB-main.zip"
GEOMETRY_PREFIX = "QUESTDB-main/geometries/xyz"
GEOMETRY_DIR = WORK_DIR / "geometries"
INPUT_DIR = WORK_DIR / "inputs"


@dataclass(frozen=True)
class QuestCase:
    key: str
    xyz_name: str
    charge: int = 0

    @property
    def zip_member(self) -> str:
        return f"{GEOMETRY_PREFIX}/{self.xyz_name}"

    @property
    def xyz_path(self) -> Path:
        return GEOMETRY_DIR / self.xyz_name

    @property
    def input_path(self) -> Path:
        return INPUT_DIR / f"quest1_{self.key}.inp"


CASES = (
    QuestCase("acetaldehyde", "acetaldehyde.xyz"),
    QuestCase("acetylene", "acetylene_1.xyz"),
    QuestCase("ammonia", "ammonia.xyz"),
    QuestCase("carbon_monoxide", "carbon_monoxide.xyz"),
    QuestCase("cyclopropene", "cyclopropene.xyz"),
    QuestCase("diazomethane", "diazomethane_1.xyz"),
    QuestCase("dinitrogen", "dinitrogen.xyz"),
    QuestCase("ethylene", "ethylene.xyz"),
    QuestCase("formaldehyde", "formaldehyde_1.xyz"),
    QuestCase("formamide", "formamide.xyz"),
    QuestCase("hydrogen_chloride", "hydrogen_chloride.xyz"),
    QuestCase("hydrogen_sulfide", "hydrogen_sulfide.xyz"),
    QuestCase("ketene", "ketene_1.xyz"),
    QuestCase("methanimine", "methanimine.xyz"),
    QuestCase("nitrosomethane", "nitrosomethane_1.xyz"),
    QuestCase("streptocyanine_c1", "streptocyanine-c1.xyz", charge=1),
    QuestCase("thioformaldehyde", "thioformaldehyde_1.xyz"),
    QuestCase("water", "water.xyz"),
)


def parse_case_filter(raw_cases: str) -> list[QuestCase]:
    if not raw_cases:
        return list(CASES)

    wanted = {token.strip().lower() for token in raw_cases.split(",") if token.strip()}
    by_key = {case.key.lower(): case for case in CASES}
    missing = sorted(wanted - set(by_key))
    if missing:
        available = ", ".join(case.key for case in CASES)
        raise SystemExit(
            f"Unknown --cases entries: {', '.join(missing)}\n"
            f"Available cases: {available}"
        )
    return [case for case in CASES if case.key.lower() in wanted]


def extract_xyz(case: QuestCase) -> Path:
    if not ZIP_PATH.is_file():
        raise FileNotFoundError(f"Missing QUEST archive: {ZIP_PATH}")

    GEOMETRY_DIR.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(ZIP_PATH) as archive:
        try:
            raw = archive.read(case.zip_member)
        except KeyError as exc:
            raise FileNotFoundError(
                f"{case.zip_member!r} not found inside {ZIP_PATH}"
            ) from exc

    case.xyz_path.write_bytes(raw)
    return case.xyz_path


def build_openqp_input(
    case: QuestCase,
    *,
    basis: str,
    functional: str,
    nstate: int,
    scf_multiplicity: int,
    target_multiplicity: int,
) -> str:
    xyz_path = case.xyz_path.relative_to(WORK_DIR)
    return f"""# QUEST1 {case.key}: triplet-reference MRSF-TDDFT
# Generated by quest1.py. Run from this directory with:
#   openqp {case.input_path.relative_to(WORK_DIR)}
#
# Reference: [scf] type=rohf, multiplicity={scf_multiplicity}
# Target roots: [tdhf] type=mrsf, multiplicity={target_multiplicity}

[input]
system={xyz_path}
charge={case.charge}
runtype=energy
basis={basis}
functional={functional}
method=tdhf
d4=False

[guess]
type=huckel
save_mol=False

[scf]
type=rohf
multiplicity={scf_multiplicity}
maxit=30
maxdiis=5
conv=1.0e-8
save_molden=False

[dftgrid]
rad_npts=96
ang_npts=302
pruned=

[tdhf]
type=mrsf
multiplicity={target_multiplicity}
nstate={nstate}
maxit=30
conv=1.0e-8
zvconv=1.0e-8
"""


def write_input(case: QuestCase, args: argparse.Namespace) -> Path:
    INPUT_DIR.mkdir(parents=True, exist_ok=True)
    text = build_openqp_input(
        case,
        basis=args.basis,
        functional=args.functional,
        nstate=args.nstate,
        scf_multiplicity=args.scf_multiplicity,
        target_multiplicity=args.target_multiplicity,
    )
    case.input_path.write_text(text, encoding="utf-8")
    return case.input_path


def run_openqp(input_path: Path) -> None:
    subprocess.run(["openqp", str(input_path)], cwd=WORK_DIR, check=True)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Prepare QUEST1 triplet-reference OpenQP MRSF-TDDFT inputs."
    )
    parser.add_argument(
        "--cases",
        default="",
        help="Comma-separated case keys to prepare. Default: all QUEST1 cases.",
    )
    parser.add_argument("--basis", default="aug-cc-pvtz")
    parser.add_argument("--functional", default="bhhlyp")
    parser.add_argument("--nstate", type=int, default=10)
    parser.add_argument(
        "--scf-multiplicity",
        type=int,
        default=3,
        help="Reference-state multiplicity. Default 3 means triplet ROHF.",
    )
    parser.add_argument(
        "--target-multiplicity",
        type=int,
        default=1,
        help="MRSF target-root multiplicity. Default 1 means singlet roots.",
    )
    parser.add_argument(
        "--run",
        action="store_true",
        help="Actually run openqp after preparing each input.",
    )
    args = parser.parse_args()

    selected_cases = parse_case_filter(args.cases)
    print(f"Preparing {len(selected_cases)} QUEST1 case(s) in {WORK_DIR}")
    print(
        "OpenQP setup: "
        f"ROHF multiplicity={args.scf_multiplicity}, "
        f"MRSF target multiplicity={args.target_multiplicity}, "
        f"functional={args.functional}, basis={args.basis}, nstate={args.nstate}"
    )

    for case in selected_cases:
        xyz_path = extract_xyz(case)
        input_path = write_input(case, args)
        print(f"{case.key:18s} xyz={xyz_path.relative_to(WORK_DIR)} inp={input_path.relative_to(WORK_DIR)}")
        if args.run:
            run_openqp(input_path)

    if not args.run:
        print("Prepared inputs only. Add --run to call openqp.")


if __name__ == "__main__":
    main()
